"""empty message

Revision ID: 24700250a0f0
Revises: 3ddfd2d4b99c
Create Date: 2020-11-05 00:24:20.242177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24700250a0f0'
down_revision = '3ddfd2d4b99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_total', sa.Column('overdraft_total', sa.Float(), nullable=True))
    op.drop_column('period_total', 'overdraft')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_total', sa.Column('overdraft', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('period_total', 'overdraft_total')
    # ### end Alembic commands ###
