"""empty message

Revision ID: 3ddfd2d4b99c
Revises: 7c4cd15d44d3
Create Date: 2020-11-02 22:28:30.163578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddfd2d4b99c'
down_revision = '7c4cd15d44d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'products_sold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('products_sold', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
