"""empty message

Revision ID: 566128da5c5d
Revises: 24700250a0f0
Create Date: 2020-11-05 00:41:48.968281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566128da5c5d'
down_revision = '24700250a0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_total', sa.Column('credit_total_begining_of_period', sa.Float(), nullable=True))
    op.add_column('period_total', sa.Column('credit_total_end_of_period', sa.Float(), nullable=True))
    op.add_column('period_total', sa.Column('deposit_credit', sa.Integer(), nullable=True))
    op.add_column('period_total', sa.Column('deposit_overdraft', sa.Integer(), nullable=True))
    op.add_column('period_total', sa.Column('overdraft_total_begining_of_period', sa.Float(), nullable=True))
    op.add_column('period_total', sa.Column('overdraft_total_end_of_period', sa.Float(), nullable=True))
    op.drop_column('period_total', 'make_deposit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_total', sa.Column('make_deposit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('period_total', 'overdraft_total_end_of_period')
    op.drop_column('period_total', 'overdraft_total_begining_of_period')
    op.drop_column('period_total', 'deposit_overdraft')
    op.drop_column('period_total', 'deposit_credit')
    op.drop_column('period_total', 'credit_total_end_of_period')
    op.drop_column('period_total', 'credit_total_begining_of_period')
    # ### end Alembic commands ###
