"""empty message

Revision ID: 62bcb007a722
Revises: e62cf73e0ff4
Create Date: 2020-10-11 10:51:14.916417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bcb007a722'
down_revision = 'e62cf73e0ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'approved')
    # ### end Alembic commands ###
