"""empty message

Revision ID: 7c4cd15d44d3
Revises: 8931ddeaf9eb
Create Date: 2020-11-02 21:58:42.103602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4cd15d44d3'
down_revision = '8931ddeaf9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('confirmed_by_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'confirmed_by_admin')
    # ### end Alembic commands ###
