"""empty message

Revision ID: 8931ddeaf9eb
Revises: 107c86aeb84b
Create Date: 2020-11-02 21:24:56.838841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8931ddeaf9eb'
down_revision = '107c86aeb84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('total_costs_per_one', sa.Float(), nullable=True))
    op.add_column('period_total', sa.Column('make_deposit', sa.Integer(), nullable=True))
    op.add_column('period_total', sa.Column('take_credit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period_total', 'take_credit')
    op.drop_column('period_total', 'make_deposit')
    op.drop_column('period', 'total_costs_per_one')
    # ### end Alembic commands ###
