"""empty message

Revision ID: 8e0173cf8553
Revises: cfc4efd84921
Create Date: 2020-10-03 23:45:27.306091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0173cf8553'
down_revision = 'cfc4efd84921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('player', sa.Integer(), nullable=True),
    sa.Column('product_A_produced', sa.Integer(), nullable=True),
    sa.Column('product_B_produced', sa.Integer(), nullable=True),
    sa.Column('product_C_produced', sa.Integer(), nullable=True),
    sa.Column('product_A_sold', sa.Integer(), nullable=True),
    sa.Column('product_B_sold', sa.Integer(), nullable=True),
    sa.Column('product_C_sold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period')
    # ### end Alembic commands ###
