"""empty message

Revision ID: a08349bb4da6
Revises: 566128da5c5d
Create Date: 2020-11-05 01:40:56.355371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08349bb4da6'
down_revision = '566128da5c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period_total', sa.Column('input_approved_by_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period_total', 'input_approved_by_admin')
    # ### end Alembic commands ###
