"""empty message

Revision ID: a751cb0894db
Revises: 0c9588f259dd
Create Date: 2020-10-02 02:18:57.067339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a751cb0894db'
down_revision = '0c9588f259dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_active')
    # ### end Alembic commands ###
