"""empty message

Revision ID: b48d8a0f384e
Revises: 28ea5a88b837
Create Date: 2020-11-02 15:18:09.318095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b48d8a0f384e'
down_revision = '28ea5a88b837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_total',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('money_total_begining_of_period', sa.Float(), nullable=True),
    sa.Column('money_total_end_of_period', sa.Float(), nullable=True),
    sa.Column('total_production_quantity', sa.Integer(), nullable=True),
    sa.Column('total_administrative_costs', sa.Float(), nullable=True),
    sa.Column('total_interest_costs', sa.Float(), nullable=True),
    sa.Column('money_total', sa.Float(), nullable=True),
    sa.Column('credit_total', sa.Float(), nullable=True),
    sa.Column('overdraft', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('period_totals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_totals',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('money_total_begining_of_period', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('money_total_end_of_period', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_production_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_administrative_costs', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_interest_costs', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('money_total', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('credit_total', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overdraft', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='period_totals_game_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='period_totals_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='period_totals_pkey')
    )
    op.drop_table('period_total')
    # ### end Alembic commands ###
