"""empty message

Revision ID: cc223bc0c344
Revises: 174f730fc6a0
Create Date: 2020-10-04 00:55:06.363223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc223bc0c344'
down_revision = '174f730fc6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('about_me', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
