"""empty message

Revision ID: cfc4efd84921
Revises: a751cb0894db
Create Date: 2020-10-03 15:59:08.292860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc4efd84921'
down_revision = 'a751cb0894db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('demand_A', sa.Integer(), nullable=True),
    sa.Column('demand_B', sa.Integer(), nullable=True),
    sa.Column('demand_C', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('product_A_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('product_B_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('product_C_count', sa.Integer(), nullable=True))
    op.drop_column('user', 'product_2')
    op.drop_column('user', 'product_1')
    op.drop_column('user', 'product_3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('product_3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('product_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('product_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'product_C_count')
    op.drop_column('user', 'product_B_count')
    op.drop_column('user', 'product_A_count')
    op.drop_table('demand')
    # ### end Alembic commands ###
