"""empty message

Revision ID: f12e16ae2ef3
Revises: 151b6febc6b5
Create Date: 2020-10-04 00:09:46.861803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12e16ae2ef3'
down_revision = '151b6febc6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('player', sa.Integer(), nullable=True),
    sa.Column('in_stock_product_A', sa.Integer(), nullable=True),
    sa.Column('in_stock_product_B', sa.Integer(), nullable=True),
    sa.Column('in_stock_product_C', sa.Integer(), nullable=True),
    sa.Column('product_A_produced', sa.Integer(), nullable=True),
    sa.Column('product_B_produced', sa.Integer(), nullable=True),
    sa.Column('product_C_produced', sa.Integer(), nullable=True),
    sa.Column('product_A_sold', sa.Integer(), nullable=True),
    sa.Column('product_B_sold', sa.Integer(), nullable=True),
    sa.Column('product_C_sold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period')
    # ### end Alembic commands ###
