"""empty message

Revision ID: 049f048fb336
Revises: 
Create Date: 2020-10-29 01:09:41.949932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049f048fb336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinput',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('produce_quantity', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.Column('marketing_costs', sa.Integer(), nullable=True),
    sa.Column('research_and_development_costs', sa.Integer(), nullable=True),
    sa.Column('marketing_research_price', sa.Boolean(), nullable=True),
    sa.Column('marketing_research_sales', sa.Boolean(), nullable=True),
    sa.Column('marketing_research_quality', sa.Boolean(), nullable=True),
    sa.Column('marketing_research_marketing_costs', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'period', 'userinput', ['userinput_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'period', type_='foreignkey')
    op.drop_table('userinput')
    # ### end Alembic commands ###
