"""empty message

Revision ID: 090cadf2ece3
Revises: 44184f3da9a6
Create Date: 2020-10-31 16:08:13.274625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090cadf2ece3'
down_revision = '44184f3da9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinput', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userinput', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userinput', type_='foreignkey')
    op.drop_column('userinput', 'user_id')
    # ### end Alembic commands ###
