"""empty message

Revision ID: 0ba447dee696
Revises: 
Create Date: 2020-10-25 13:37:17.396999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba447dee696'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand', sa.Column('demand_scenario_id', sa.Integer(), nullable=True))
    op.drop_constraint('demand_game_id_fkey', 'demand', type_='foreignkey')
    op.drop_column('demand', 'game_id')
    op.add_column('game', sa.Column('demand_scenario_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'demand_scenario_id')
    op.add_column('demand', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('demand_game_id_fkey', 'demand', 'game', ['game_id'], ['id'])
    op.drop_column('demand', 'demand_scenario_id')
    # ### end Alembic commands ###
