"""empty message

Revision ID: 0c9588f259dd
Revises: cc08d68272ed
Create Date: 2020-10-02 01:55:48.831669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9588f259dd'
down_revision = 'cc08d68272ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'game_id')
    # ### end Alembic commands ###
