"""empty message

Revision ID: 11e4be584da8
Revises: d8491e3f7bf0
Create Date: 2020-11-01 20:28:01.823916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e4be584da8'
down_revision = 'd8491e3f7bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('research_marketing', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('research_price', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('research_quality', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'research_quality')
    op.drop_column('period', 'research_price')
    op.drop_column('period', 'research_marketing')
    # ### end Alembic commands ###
