"""empty message

Revision ID: 12db6a4d26b2
Revises: 693f0d01f119
Create Date: 2020-11-01 20:42:44.231452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12db6a4d26b2'
down_revision = '693f0d01f119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('research_sales', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'research_sales')
    # ### end Alembic commands ###
