"""empty message

Revision ID: 151b6febc6b5
Revises: 8e0173cf8553
Create Date: 2020-10-03 23:56:01.570371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151b6febc6b5'
down_revision = '8e0173cf8553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('in_stock_product_A', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('in_stock_product_B', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('in_stock_product_C', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'in_stock_product_C')
    op.drop_column('period', 'in_stock_product_B')
    op.drop_column('period', 'in_stock_product_A')
    # ### end Alembic commands ###
