"""empty message

Revision ID: 174f730fc6a0
Revises: 55fb3fc52354
Create Date: 2020-10-04 00:23:02.189602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174f730fc6a0'
down_revision = '55fb3fc52354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('player', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
