"""empty message

Revision ID: 1e42320f62f5
Revises: 0ba447dee696
Create Date: 2020-10-25 13:40:58.856153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e42320f62f5'
down_revision = '0ba447dee696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_scenario_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('demand_A', sa.Integer(), nullable=True),
    sa.Column('demand_B', sa.Integer(), nullable=True),
    sa.Column('demand_C', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demand')
    # ### end Alembic commands ###
