"""empty message

Revision ID: 216625ea8f3a
Revises: fdf451e47bb4
Create Date: 2020-10-27 01:36:11.405416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216625ea8f3a'
down_revision = 'fdf451e47bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period_product')
    op.drop_table('product')
    op.add_column('period', sa.Column('product_a_marketing', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_a_quality', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_b_marketing', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_b_quality', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_c_marketing', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_c_quality', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'product_c_quality')
    op.drop_column('period', 'product_c_marketing')
    op.drop_column('period', 'product_b_quality')
    op.drop_column('period', 'product_b_marketing')
    op.drop_column('period', 'product_a_quality')
    op.drop_column('period', 'product_a_marketing')
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('period_product',
    sa.Column('period_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('produced', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], name='period_product_period_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='period_product_product_id_fkey'),
    sa.PrimaryKeyConstraint('period_id', 'product_id', name='period_product_pkey')
    )
    # ### end Alembic commands ###
