"""empty message

Revision ID: 23c62a241710
Revises: 7f37204ca399
Create Date: 2020-11-01 14:00:08.717835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c62a241710'
down_revision = '7f37204ca399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('marketing_index_max', sa.Float(), nullable=True))
    op.add_column('scenario', sa.Column('marketing_index_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'marketing_index_min')
    op.drop_column('scenario', 'marketing_index_max')
    # ### end Alembic commands ###
