"""empty message

Revision ID: 2432d109d0d9
Revises: a99698cb59bf
Create Date: 2020-10-11 22:57:15.655554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2432d109d0d9'
down_revision = 'a99698cb59bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'product_b_count')
    op.drop_column('user', 'product_c_count')
    op.drop_column('user', 'money')
    op.drop_column('user', 'product_a_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('product_a_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('money', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('product_c_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('product_b_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
