"""empty message

Revision ID: 37ba8893575b
Revises: 12db6a4d26b2
Create Date: 2020-11-02 00:18:12.075942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ba8893575b'
down_revision = '12db6a4d26b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('combined_score', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('demand', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('direct_sells', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('market_share', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('recalc_marketing', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('recalc_price', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('recalc_quality', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('secondary_sells', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('sell_price', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('total_sells', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('unsatisfied_demand', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'unsatisfied_demand')
    op.drop_column('period', 'total_sells')
    op.drop_column('period', 'sell_price')
    op.drop_column('period', 'secondary_sells')
    op.drop_column('period', 'recalc_quality')
    op.drop_column('period', 'recalc_price')
    op.drop_column('period', 'recalc_marketing')
    op.drop_column('period', 'market_share')
    op.drop_column('period', 'direct_sells')
    op.drop_column('period', 'demand')
    op.drop_column('period', 'combined_score')
    # ### end Alembic commands ###
