"""empty message

Revision ID: 48ef42207bad
Revises: 23c62a241710
Create Date: 2020-11-01 14:22:51.729812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ef42207bad'
down_revision = '23c62a241710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('index_marketing', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('index_quality', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'index_quality')
    op.drop_column('period', 'index_marketing')
    # ### end Alembic commands ###
