"""empty message

Revision ID: 6e0723586417
Revises: 090cadf2ece3
Create Date: 2020-10-31 16:09:18.031534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0723586417'
down_revision = '090cadf2ece3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinput', sa.Column('period_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinput', 'period_number')
    # ### end Alembic commands ###
