"""empty message

Revision ID: 73c7e63d4299
Revises: b0413a7f75cf
Create Date: 2020-10-28 23:54:58.502880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c7e63d4299'
down_revision = 'b0413a7f75cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'period', 'product', ['product_id'], ['id'])
    op.add_column('userinput', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userinput', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userinput', type_='foreignkey')
    op.drop_column('userinput', 'product_id')
    op.drop_constraint(None, 'period', type_='foreignkey')
    op.drop_column('period', 'product_id')
    # ### end Alembic commands ###
