"""empty message

Revision ID: 7b243c8226df
Revises: 37ba8893575b
Create Date: 2020-11-02 08:45:14.987858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b243c8226df'
down_revision = '37ba8893575b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_totals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('money_total_begining_of_period', sa.Float(), nullable=True),
    sa.Column('money_total_end_of_period', sa.Float(), nullable=True),
    sa.Column('total_production_quantity', sa.Integer(), nullable=True),
    sa.Column('total_administrative_costs', sa.Float(), nullable=True),
    sa.Column('total_interest_costs', sa.Float(), nullable=True),
    sa.Column('money_total', sa.Float(), nullable=True),
    sa.Column('credit_total', sa.Float(), nullable=True),
    sa.Column('overdraft', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'money_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('period_totals')
    # ### end Alembic commands ###
