"""empty message

Revision ID: 7f37204ca399
Revises: 43c6b1efa89c
Create Date: 2020-11-01 13:40:40.442033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f37204ca399'
down_revision = '43c6b1efa89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('accumulated_proffit', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('is_producing', sa.Boolean(), nullable=True))
    op.add_column('period', sa.Column('labor_costs', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('net_proffit', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('product_manager_costs', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('total_costs', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('total_non_production_costs', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('total_production_cost', sa.Float(), nullable=True))
    op.drop_column('period', 'labot_costs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('labot_costs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('period', 'total_production_cost')
    op.drop_column('period', 'total_non_production_costs')
    op.drop_column('period', 'total_costs')
    op.drop_column('period', 'product_manager_costs')
    op.drop_column('period', 'net_proffit')
    op.drop_column('period', 'labor_costs')
    op.drop_column('period', 'is_producing')
    op.drop_column('period', 'accumulated_proffit')
    # ### end Alembic commands ###
