"""empty message

Revision ID: 8bb8d46c25df
Revises: c532b99aa069
Create Date: 2020-10-28 23:40:14.632434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb8d46c25df'
down_revision = 'c532b99aa069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinput',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('produce_quantity', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.Column('marketing_costs', sa.Integer(), nullable=True),
    sa.Column('research_and_development_costs', sa.Integer(), nullable=True),
    sa.Column('marketing_research_price', sa.Integer(), nullable=True),
    sa.Column('marketing_research_sales', sa.Integer(), nullable=True),
    sa.Column('marketing_research_quality', sa.Integer(), nullable=True),
    sa.Column('marketing_research_marketing_costs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('period', sa.Column('administrative_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('gross_proffit', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('income_from_sells', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('interest_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('labot_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('marketing_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('marketing_research_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('material_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('other_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('products_in_stock_beggining_of_period', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('products_in_stock_end_of_period', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('products_sold', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('research_and_development_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('storage_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('transport_costs', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('userinput_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'period', 'userinput', ['userinput_id'], ['id'])
    op.drop_column('period', 'product_b_actual_quality')
    op.drop_column('period', 'product_a_quality_investment')
    op.drop_column('period', 'product_c_produced')
    op.drop_column('period', 'product_a_sold')
    op.drop_column('period', 'product_a_produced')
    op.drop_column('period', 'product_c_actual_quality')
    op.drop_column('period', 'product_b_produced')
    op.drop_column('period', 'price_product_c')
    op.drop_column('period', 'product_a_actual_quality')
    op.drop_column('period', 'product_b_quality_investment')
    op.drop_column('period', 'product_a_marketing')
    op.drop_column('period', 'in_stock_product_a')
    op.drop_column('period', 'product_c_sold')
    op.drop_column('period', 'in_stock_product_c')
    op.drop_column('period', 'money')
    op.drop_column('period', 'product_c_quality_investment')
    op.drop_column('period', 'in_stock_product_b')
    op.drop_column('period', 'product_b_sold')
    op.drop_column('period', 'product_b_marketing')
    op.drop_column('period', 'price_product_b')
    op.drop_column('period', 'price_product_a')
    op.drop_column('period', 'product_c_marketing')
    op.add_column('user', sa.Column('money_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'money_total')
    op.add_column('period', sa.Column('product_c_marketing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('price_product_a', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('price_product_b', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_b_marketing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_b_sold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('in_stock_product_b', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_c_quality_investment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('money', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('in_stock_product_c', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_c_sold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('in_stock_product_a', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_a_marketing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_b_quality_investment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_a_actual_quality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('price_product_c', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_b_produced', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_c_actual_quality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_a_produced', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_a_sold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_c_produced', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_a_quality_investment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_b_actual_quality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'period', type_='foreignkey')
    op.drop_column('period', 'userinput_id')
    op.drop_column('period', 'transport_costs')
    op.drop_column('period', 'storage_costs')
    op.drop_column('period', 'research_and_development_costs')
    op.drop_column('period', 'products_sold')
    op.drop_column('period', 'products_in_stock_end_of_period')
    op.drop_column('period', 'products_in_stock_beggining_of_period')
    op.drop_column('period', 'other_costs')
    op.drop_column('period', 'material_costs')
    op.drop_column('period', 'marketing_research_costs')
    op.drop_column('period', 'marketing_costs')
    op.drop_column('period', 'labot_costs')
    op.drop_column('period', 'interest_costs')
    op.drop_column('period', 'income_from_sells')
    op.drop_column('period', 'gross_proffit')
    op.drop_column('period', 'administrative_costs')
    op.drop_table('userinput')
    op.drop_table('product')
    # ### end Alembic commands ###
