"""empty message

Revision ID: 9fa2a3bee1c3
Revises: 8d38fa564947
Create Date: 2020-10-31 00:04:33.640961

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9fa2a3bee1c3'
down_revision = '8d38fa564947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for product in [1, 2, 3]:
        cost_materials = product + 2
        cost_unpredicted = 1000 if product == 3 else 0

        for period in range(1, 21):
            op.execute('INSERT INTO "scenario" (id, demand_scenario_id, period, product_id, '
                       'demand_quantity, sensitivity_price, sensitivity_quality, sensitivity_marketing, '
                       'correction_cost_labor, correction_cost_materials_for_one_product, '
                       'cost_unpredicted, cost_materials_for_one_product, cost_labor, investment_for_one_marketing, '
                       'investment_for_one_quality, quality_index_min, quality_index_max, marketing_keep_effect, '
                       'base_value_rand_quality, cost_transport, cost_storage, cost_fixed_administrative, '
                       'cost_product_manager, cost_new_product_manager, price_research, interest_credit, '
                       'interest_overdraft, max_price) '
                       f'VALUES (default, 1, {period}, {product}, 3850, 1, 1.05, 0.95, 1, 1, {cost_unpredicted}, '
                       f'{cost_materials}, 5, 200, 1000, 5, 5, 0.5, 0.7, 1.5, 0.5, 5000, 1000, 1500, 500, 0.05, '
                       f'0.1, 50);')

    # ### end Alembic commands ###
