"""empty message

Revision ID: ac85acfbd3c8
Revises: 2432d109d0d9
Create Date: 2020-10-25 12:51:28.506562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac85acfbd3c8'
down_revision = '2432d109d0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('price_product_a', sa.Numeric(), nullable=True),
    sa.Column('price_product_b', sa.Numeric(), nullable=True),
    sa.Column('price_product_c', sa.Numeric(), nullable=True),
    sa.Column('in_stock_product_a', sa.Integer(), nullable=True),
    sa.Column('in_stock_product_b', sa.Integer(), nullable=True),
    sa.Column('in_stock_product_c', sa.Integer(), nullable=True),
    sa.Column('product_a_produced', sa.Integer(), nullable=True),
    sa.Column('product_b_produced', sa.Integer(), nullable=True),
    sa.Column('product_c_produced', sa.Integer(), nullable=True),
    sa.Column('product_a_sold', sa.Integer(), nullable=True),
    sa.Column('product_b_sold', sa.Integer(), nullable=True),
    sa.Column('product_c_sold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period')
    # ### end Alembic commands ###
