"""empty message

Revision ID: b0413a7f75cf
Revises: 8bb8d46c25df
Create Date: 2020-10-28 23:51:59.361423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0413a7f75cf'
down_revision = '8bb8d46c25df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinput',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('produce_quantity', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.Column('marketing_costs', sa.Integer(), nullable=True),
    sa.Column('research_and_development_costs', sa.Integer(), nullable=True),
    sa.Column('marketing_research_price', sa.Integer(), nullable=True),
    sa.Column('marketing_research_sales', sa.Integer(), nullable=True),
    sa.Column('marketing_research_quality', sa.Integer(), nullable=True),
    sa.Column('marketing_research_marketing_costs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'period', 'userinput', ['userinput_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'period', type_='foreignkey')
    op.drop_table('userinput')
    # ### end Alembic commands ###
