"""empty message

Revision ID: bdef6cebc7e5
Revises: 1871f331ff29
Create Date: 2020-11-02 11:51:34.066178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdef6cebc7e5'
down_revision = '1871f331ff29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_per_product', 'interest_overdraft')
    op.drop_column('scenario_per_product', 'interest_credit')
    op.drop_column('scenario_per_product', 'cost_fixed_administrative')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_per_product', sa.Column('cost_fixed_administrative', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scenario_per_product', sa.Column('interest_credit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('scenario_per_product', sa.Column('interest_overdraft', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
