"""empty message

Revision ID: c532b99aa069
Revises: 216625ea8f3a
Create Date: 2020-10-27 01:38:40.333673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c532b99aa069'
down_revision = '216625ea8f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('product_a_actual_quality', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_a_quality_investment', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_b_actual_quality', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_b_quality_investment', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_c_actual_quality', sa.Integer(), nullable=True))
    op.add_column('period', sa.Column('product_c_quality_investment', sa.Integer(), nullable=True))
    op.drop_column('period', 'product_c_quality')
    op.drop_column('period', 'product_b_quality')
    op.drop_column('period', 'product_a_quality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('product_a_quality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_b_quality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('period', sa.Column('product_c_quality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('period', 'product_c_quality_investment')
    op.drop_column('period', 'product_c_actual_quality')
    op.drop_column('period', 'product_b_quality_investment')
    op.drop_column('period', 'product_b_actual_quality')
    op.drop_column('period', 'product_a_quality_investment')
    op.drop_column('period', 'product_a_actual_quality')
    # ### end Alembic commands ###
