"""empty message

Revision ID: d8491e3f7bf0
Revises: 48ef42207bad
Create Date: 2020-11-01 17:45:21.831260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8491e3f7bf0'
down_revision = '48ef42207bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('consolidated_marketing_budget', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('consolidated_rnd_budget', sa.Float(), nullable=True))
    op.add_column('period', sa.Column('random_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'random_value')
    op.drop_column('period', 'consolidated_rnd_budget')
    op.drop_column('period', 'consolidated_marketing_budget')
    # ### end Alembic commands ###
