"""empty message

Revision ID: e62cf73e0ff4
Revises: cc223bc0c344
Create Date: 2020-10-04 01:21:15.761584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62cf73e0ff4'
down_revision = 'cc223bc0c344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('price_product_A', sa.Numeric(), nullable=True))
    op.add_column('period', sa.Column('price_product_B', sa.Numeric(), nullable=True))
    op.add_column('period', sa.Column('price_product_C', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'price_product_C')
    op.drop_column('period', 'price_product_B')
    op.drop_column('period', 'price_product_A')
    # ### end Alembic commands ###
