"""empty message

Revision ID: fa1466763817
Revises: 9fa2a3bee1c3
Create Date: 2020-10-31 00:34:12.380697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1466763817'
down_revision = '9fa2a3bee1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_scenario_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('demand_quantity', sa.Integer(), nullable=True),
    sa.Column('sensitivity_price', sa.Float(), nullable=True),
    sa.Column('sensitivity_quality', sa.Float(), nullable=True),
    sa.Column('sensitivity_marketing', sa.Float(), nullable=True),
    sa.Column('correction_cost_labor', sa.Float(), nullable=True),
    sa.Column('correction_cost_materials_for_one_product', sa.Float(), nullable=True),
    sa.Column('cost_unpredicted', sa.Integer(), nullable=True),
    sa.Column('cost_materials_for_one_product', sa.Float(), nullable=True),
    sa.Column('cost_labor', sa.Float(), nullable=True),
    sa.Column('investment_for_one_marketing', sa.Integer(), nullable=True),
    sa.Column('investment_for_one_quality', sa.Integer(), nullable=True),
    sa.Column('quality_index_min', sa.Float(), nullable=True),
    sa.Column('quality_index_max', sa.Float(), nullable=True),
    sa.Column('marketing_keep_effect', sa.Float(), nullable=True),
    sa.Column('base_value_rand_quality', sa.Float(), nullable=True),
    sa.Column('cost_transport', sa.Float(), nullable=True),
    sa.Column('cost_storage', sa.Float(), nullable=True),
    sa.Column('cost_fixed_administrative', sa.Integer(), nullable=True),
    sa.Column('cost_product_manager', sa.Integer(), nullable=True),
    sa.Column('cost_new_product_manager', sa.Integer(), nullable=True),
    sa.Column('price_research', sa.Integer(), nullable=True),
    sa.Column('interest_credit', sa.Float(), nullable=True),
    sa.Column('interest_overdraft', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinput',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('produce_quantity', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.Column('marketing_costs', sa.Integer(), nullable=True),
    sa.Column('research_and_development_costs', sa.Integer(), nullable=True),
    sa.Column('marketing_research_price', sa.Boolean(), nullable=True),
    sa.Column('marketing_research_sales', sa.Boolean(), nullable=True),
    sa.Column('marketing_research_quality', sa.Boolean(), nullable=True),
    sa.Column('marketing_research_marketing_costs', sa.Boolean(), nullable=True),
    sa.Column('approved_by_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('period',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('userinput_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('income_from_sells', sa.Integer(), nullable=True),
    sa.Column('labot_costs', sa.Integer(), nullable=True),
    sa.Column('material_costs', sa.Integer(), nullable=True),
    sa.Column('gross_proffit', sa.Integer(), nullable=True),
    sa.Column('marketing_costs', sa.Integer(), nullable=True),
    sa.Column('research_and_development_costs', sa.Integer(), nullable=True),
    sa.Column('transport_costs', sa.Integer(), nullable=True),
    sa.Column('storage_costs', sa.Integer(), nullable=True),
    sa.Column('administrative_costs', sa.Integer(), nullable=True),
    sa.Column('marketing_research_costs', sa.Integer(), nullable=True),
    sa.Column('interest_costs', sa.Integer(), nullable=True),
    sa.Column('other_costs', sa.Integer(), nullable=True),
    sa.Column('products_sold', sa.Integer(), nullable=True),
    sa.Column('products_in_stock_beggining_of_period', sa.Integer(), nullable=True),
    sa.Column('products_in_stock_end_of_period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['userinput_id'], ['userinput.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('period')
    op.drop_table('userinput')
    op.drop_table('scenario')
    # ### end Alembic commands ###
